In [ ]:
import tensorflow as tf
import numpy as np

**Task 1**

In [ ]:
a = tf.constant

In [ ]:
# define a constant
a = tf.constant(5)

# define variables
b = tf.Variable(2)
c = tf.Variable(3)

In [ ]:
# define two 1d tensors
t1 = tf.constant([1, 2, 3])
t2 = tf.constant([4, 5, 6])

In [ ]:
# concat
concat = tf.concat([t1, t2], axis = 0)
print(concat)

tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)


In [ ]:
# add
sum = tf.add(t1, t2)
print(sum)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [ ]:
# multiply
prod = tf.multiply(t1, t2)
print(prod)

tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


In [ ]:
# reduced mean
rmean = tf.reduce_mean(t1)
print(rmean)

tf.Tensor(2, shape=(), dtype=int32)


In [ ]:
# reduced sum
rsum = tf.reduce_sum(t1)
print(rsum)

tf.Tensor(6, shape=(), dtype=int32)


**Task 2**

In [ ]:
mat1 = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]])
mat2 = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]])

In [ ]:
trans_mat1 = tf.transpose(mat1)
print(trans_mat1)

tf.Tensor(
[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]], shape=(3, 3), dtype=float32)


In [ ]:
matrix_mult = tf.matmul(mat1, mat2)
print(matrix_mult)

tf.Tensor(
[[ 30.  36.  42.]
 [ 66.  81.  96.]
 [102. 126. 150.]], shape=(3, 3), dtype=float32)


In [ ]:
element_mult = tf.multiply(mat1, mat2)
print(element_mult)

tf.Tensor(
[[ 1.  4.  9.]
 [16. 25. 36.]
 [49. 64. 81.]], shape=(3, 3), dtype=float32)


In [ ]:
det_mat1 = tf.linalg.det(mat1)
print(det_mat1)

tf.Tensor(0.0, shape=(), dtype=float32)


**Task 3**

In [ ]:
def f(x):
  return x**3

def compute_derivative(x):
  x = tf.Variable(x)
  with tf.GradientTape() as tape:
    tape.watch(x)
    y = f(x)
  return tape.gradient(y, x)

def compute_higher_order_derivative(x, order = 2):
  y = x
  for _ in range(order):
    y = compute_derivative(y)
  return y

In [ ]:
x = 2.0

first_derivative = compute_derivative(x)
print(first_derivative)

second_derivative = compute_higher_order_derivative(x, order = 2)
print(second_derivative)

tf.Tensor(12.0, shape=(), dtype=float32)
tf.Tensor(432.0, shape=(), dtype=float32)


**Task 4**

In [ ]:
W_shape = (4, 3)
X_shape = (3, 1)
b_shape = (4, 1)

W = tf.random.normal(W_shape)
X = tf.random.normal(X_shape)
b = tf.random.normal(b_shape)

print(W)
print(X)
print(b)

tf.Tensor(
[[-1.1761868   1.8560488  -2.192978  ]
 [-0.5048069  -0.6576398  -1.0237944 ]
 [ 0.4955692  -0.8441024   0.8126065 ]
 [-1.7304066   0.38012192  1.7870578 ]], shape=(4, 3), dtype=float32)
tf.Tensor(
[[-1.2203166]
 [ 0.8739429]
 [ 0.388205 ]], shape=(3, 1), dtype=float32)
tf.Tensor(
[[-1.6266369 ]
 [ 0.31573927]
 [ 1.9272728 ]
 [ 1.1673367 ]], shape=(4, 1), dtype=float32)


In [ ]:
result = tf.matmul(W, X) + b
print(result)

tf.Tensor(
[[ 0.5794393 ]
 [-0.04041821]
 [ 0.900282  ]
 [ 4.30493   ]], shape=(4, 1), dtype=float32)


**Task 5**

In [ ]:
sigmoid_var = tf.Variable(2.0)

In [ ]:
with tf.GradientTape() as tape:
  y = tf.sigmoid(sigmoid_var)
dy_dx = tape.gradient(y, sigmoid_var)
print(dy_dx)

tf.Tensor(0.104993574, shape=(), dtype=float32)
